#!/usr/bin/env python3
"""Photo → brick grid for an object sculpture (the object path).

usage: python3 trace_object.py <spec.json>   (run from the project dir)

spec = {
  "photo": "reference/photo.jpg",
  "grid": {"x0": 322, "y0": 50, "sx": 25, "sy": 10, "cols": 21, "rows": 150},   # px per stud across, px per plate down
  "classes": [                                  # later entries win; one letter per class
    {"id": "B", "poly": [[x, y], ...]},         # hand-traced polygon (use when colour can't separate object from backdrop)
    {"id": "N", "mask": {"sat_gt": 0.28, "val_gt": 0.35, "warm": true}, "y": [322, 1030], "largest": true},
       # mask keys: sat_gt sat_lt val_gt val_lt warm close(=3 closing iterations); class keys: poly | mask, y [y0,y1],
       # x [x0,x1], largest (keep the biggest blob), fill_holes (default true), within (intersect an earlier class)
    {"id": "G", "poly": [...], "within": "B"}   # only where an earlier class already is
  ],
  "min_frac": 0.45,                             # share of a cell that must be inside to count
  "fill_rows": ["N"],                           # close single-cell gaps inside these classes, per row
  "details": {...}                              # passed through untouched (px coords of hardware, dots, etc.)
}
Writes trace/<name>.json, trace/<name>.js (ES module, `export default`) and trace/grid.png (preview).
Cell (col c, row r) sits at photo px (x0 + c*sx, y0 + r*sy); row 0 is the TOP. In scene.js, stack rows bottom-up.
Choosing the grid: sx = the object's width in px / the studs you want across it (15 to 25 is a good sculpture size);
sy = sx * 0.4 keeps proportions (a plate is 0.4 studs tall); x0, y0 = just outside the object's top-left;
cols = width / sx + 1, rows = height / sy + 1. Trace the side silhouette: a photo shot from above adds a rim
ellipse that makes round objects a few plates too tall.
"""
import json, os, sys
import numpy as np
from PIL import Image, ImageDraw
try:
    from scipy import ndimage
except ImportError:
    sys.exit('error: scipy is required: pip install -r scripts/requirements.txt')

spec = json.load(open(sys.argv[1]))
name = os.path.splitext(os.path.basename(sys.argv[1]))[0]
im = Image.open(spec['photo']).convert('RGB'); W, H = im.size
a = np.asarray(im).astype(np.float32) / 255
mx, mn = a.max(-1), a.min(-1); sat = (mx - mn) / (mx + 1e-6); val = mx
R, Gc, B = a[..., 0], a[..., 1], a[..., 2]

def poly(pts):
    m = Image.new('L', (W, H), 0); ImageDraw.Draw(m).polygon([tuple(p) for p in pts], fill=1); return np.asarray(m).astype(bool)

def colour(rule):
    m = np.ones((H, W), bool)
    if 'sat_gt' in rule: m &= sat > rule['sat_gt']
    if 'sat_lt' in rule: m &= sat < rule['sat_lt']
    if 'val_gt' in rule: m &= val > rule['val_gt']
    if 'val_lt' in rule: m &= val < rule['val_lt']
    if rule.get('warm'): m &= (R > Gc) & (Gc > B)
    return ndimage.binary_closing(m, iterations=rule.get('close', 3))

masks = {}
for c in spec['classes']:
    m = poly(c['poly']) if 'poly' in c else colour(c['mask'])
    if 'y' in c: m[:c['y'][0]] = False; m[c['y'][1]:] = False
    if 'x' in c: m[:, :c['x'][0]] = False; m[:, c['x'][1]:] = False
    if c.get('largest'):
        lab, n = ndimage.label(m)
        if n: m = lab == (np.argmax(ndimage.sum(m, lab, range(1, n + 1))) + 1)
    if c.get('fill_holes', True): m = ndimage.binary_fill_holes(m)
    if 'within' in c: m &= masks[c['within']]
    masks[c['id']] = m

g = spec['grid']; x0, y0, sx, sy = g['x0'], g['y0'], g['sx'], g['sy']
th = spec.get('min_frac', 0.45)
rows = []
for r in range(g['rows']):
    line = ''
    for c in range(g['cols']):
        X, Y = int(x0 + c * sx), int(y0 + r * sy)
        ch = '.'
        for cl in spec['classes']:
            if masks[cl['id']][Y:int(Y + sy), X:int(X + sx)].mean() > th: ch = cl['id']
        line += ch
    rows.append(line)
for cls in spec.get('fill_rows', []):
    for i, line in enumerate(rows):
        idx = [k for k, ch in enumerate(line) if ch == cls]
        if idx: rows[i] = ''.join(cls if (min(idx) <= k <= max(idx) and ch == '.') else ch for k, ch in enumerate(line))

out = dict(X0=x0, Y0=y0, SX=sx, SY=sy, rows=rows, details=spec.get('details', {}), photoW=W, photoH=H)
os.makedirs('trace', exist_ok=True)
json.dump(out, open(f'trace/{name}.json', 'w'), indent=1)
open(f'trace/{name}.js', 'w').write('// generated by trace_object.py: photo → brick grid\nexport default ' + json.dumps(out) + ';\n')
pal = {}
pv = Image.new('RGB', (g['cols'] * 8, g['rows'] * 3), (50, 50, 55)); d = ImageDraw.Draw(pv)
for r, line in enumerate(rows):
    for c, ch in enumerate(line):
        if ch == '.': continue
        if ch not in pal:   # preview colour = mean photo colour of that class
            pal[ch] = tuple(int(v * 255) for v in a[masks[ch]].mean(0)) if masks[ch].any() else (200, 200, 200)
        d.rectangle([c * 8, r * 3, c * 8 + 7, r * 3 + 2], fill=pal[ch])
pv.save('trace/grid.png')
print(f"{g['cols']}x{g['rows']} cells →", {k: sum(l.count(k) for l in rows) for k in masks})
